export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const USERS_LOADING = 'USERS_LOADING';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const CHANGE_PASSWORD_USER = 'CHANGE_PASSWORD_USER';
export const MARK_USER_NOTIFICATION_AS_READ = 'MARK_USER_NOTIFICATION_AS_READ';

export const GET_COUNTRIES = 'GET_COUNTRIES';
// export const GET_COUNTRY = 'GET_COUNTRY';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const EDIT_COUNTRY = 'EDIT_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';

export const GET_CINEMAS = 'GET_CINEMAS';
// export const GET_CINEMA = 'GET_CINEMA';
export const ADD_CINEMA = 'ADD_CINEMA';
export const EDIT_CINEMA = 'EDIT_CINEMA';
export const DELETE_CINEMA = 'DELETE_CINEMA';

export const GET_MOVIES = 'GET_MOVIES';
// export const GET_MOVIE = 'GET_MOVIE';
export const ADD_MOVIE = 'ADD_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const DISTRIBUTE_MOVIE = 'DISTRIBUTE_MOVIE';
export const REDISTRIBUTE_MOVIE = 'REDISTRIBUTE_MOVIE';
export const ASSIGN_MOVIE_CINEMAS = 'ASSIGN_MOVIE_CINEMAS';
export const DEASSIGN_MOVIE_CINEMAS = 'DEASSIGN_MOVIE_CINEMAS';
export const SEND_KDMS = 'SEND_KDMS';
export const ADD_MOVIE_VERSION        = 'ADD_MOVIE_VERSION';
export const EDIT_MOVIE_VERSION       = 'EDIT_MOVIE_VERSION';
export const DELETE_MOVIE_VERSION     = 'DELETE_MOVIE_VERSION';
export const DISTRIBUTE_MOVIE_VERSION = 'DISTRIBUTE_MOVIE_VERSION';
export const GET_MOVIE_USERS = 'GET_MOVIE_USERS';
export const GET_MOVIES_ASSIGNED_TO_USER = 'GET_MOVIES_ASSIGNED_TO_USER';
export const GET_MOVIE_VERSIONS_ASSIGNED_TO_USER = 'GET_MOVIE_VERSIONS_ASSIGNED_TO_USER';
// export const ASSIGN_MOVIE_VERSIONS_CINEMAS = 'ASSIGN_MOVIE_VERSIONS_CINEMAS';




export const GET_SCREENS = 'GET_SCREENS';
// export const GET_SCREEN = 'GET_SCREEN';
export const ADD_SCREEN = 'ADD_SCREEN';
export const EDIT_SCREEN = 'EDIT_SCREEN';
export const DELETE_SCREEN = 'DELETE_SCREEN';


export const IS_LOADING = 'IS_LOADING';
export const FINISHED_LOADING = 'FINISHED_LOADING';

export const IS_LOADING_IN_DIALOG = 'IS_LOADING_IN_DIALOG';
export const FINISHED_LOADING_IN_DIALOG = 'FINISHED_LOADING_IN_DIALOG';


export const GET_DISTRIBUTORS_ACTIONS = 'GET_DISTRIBUTORS_ACTIONS_REPORT';



